# The class cannot be named by Pascal or camel case.
# The class cannot be named by Pascal or camel case.
# If it is not used, the corresponding structure will not be set,
# and it will not be read naturally.

#---------------Infrastructure configuration---------------------#
etcd:
  etcdSchema: openim  #默认即可
  etcdAddr: [ 127.0.0.1:2379 ] #单机部署时，默认即可(etcd地址)
  userName:
  password:
  secret:

mysql:
  dbMysqlAddress: [ 127.0.0.1:13306 ] #mysql地址 目前仅支持单机，默认即可
  dbMysqlUserName:  #mysql用户名，建议修改
  dbMysqlPassword:  # mysql密码，建议修改
  dbMysqlDatabaseName: openIM_v2 #默认即可
  dbMaxOpenConns: 100 # 最大开启连接
  dbMaxIdleConns: 10 # 空闲连接数
  dbMaxLifeTime: 5 #连接存活时间
  logLevel: 1 #1=slient 2=error 3=warn 4=info

kafka:
  SASLUserName:
  SASLPassword:
  ws2mschat:
    addr: [ 127.0.0.1:9092 ] #kafka配置，默认即可
    topic: "ws2ms_chat" #用于mongo和mysql保存消息
  consumergroupid:
    msgToTransfer: mongo
    msgToMySql: mysql

#---------------Internal service configuration---------------------#

# The service ip default is empty,
# automatically obtain the machine's valid network card ip as the service ip,
# otherwise the configuration ip is preferred
#如果是单机模式，用0.0.0.0或者不填，默认即可
serverip: 0.0.0.0

#作为rpc时，注册到etcd的地址，单机默认即可，如果是集群部署，需要修改（具体使用内网地址还是外网地址，要依情况而定，目的是api/gateway能访问到）
rpcRegisterIP:
#默认即可
listenIP: 0.0.0.0

rpcport: #rpc服务端口 默认即可
  openImMessagePort: [ 10130 ] # rpc im消息端口
  openImMessageGatewayPort: [ 10140 ]

rpcregistername: #rpc注册服务名，默认即可
  openImMsgName: Msg
log:
  storageLocation: ../logs/  # 持久化地址
  rotationTime: 24 # 24小时
  remainRotationCount: 2 #日志数量
  #日志级别 6表示全都打印，测试阶段建议设置为6
  remainLogLevel: 6

longconnsvr:
  openImWsPort: [ 10001 ] # ws服务端口，默认即可，要开放此端口或做nginx转发
  websocketMaxConnNum: 10000 # 最大连接数
  websocketMaxMsgLen: 4096 # 最大读取消息
  websocketTimeOut: 10 # socket连接超时时间

# prometheus每个服务监听的端口数量需要和rpc port保持一致
prometheus:
  messageGatewayPrometheusPort: [ 20140 ] ## 消息网关prometheus的端口