# The class cannot be named by Pascal or camel case.
# The class cannot be named by Pascal or camel case.
# If it is not used, the corresponding structure will not be set,
# and it will not be read naturally.

#---------------Infrastructure configuration---------------------#
etcd:
  etcdSchema: openim  #默认即可
  etcdAddr: [ 127.0.0.1:2379 ] #单机部署时，默认即可(etcd地址)
  userName:
  password:
  secret:

mysql:
  dbMysqlAddress: [ 127.0.0.1:3306 ] #mysql地址 目前仅支持单机，默认即可
  dbMysqlUserName: root  #mysql用户名，建议修改
  dbMysqlPassword: 123456 # mysql密码，建议修改
  dbMysqlDatabaseName: openIM_v2 #默认即可
  dbMaxOpenConns: 100 # 最大开启连接
  dbMaxIdleConns: 10 # 空闲连接数
  dbMaxLifeTime: 5 #连接存活时间
  logLevel: 1 #1=slient 2=error 3=warn 4=info

redis:
  dbAddress: [ 127.0.0.1:6379 ] #redis地址 单机时，填写一个地址即可，使用redis集群时候，填写集群中多个节点地址（主从地址都可以填写，增加容灾能力），默认即可
  dbUserName:     #only redis version 6.0+ need username
  dbPassWord:  #redis密码 建议修改
  enableCluster: false #如果外部redis以集群方式启动，需要打开此开关

kafka:
  SASLUserName:
  SASLPassword:
  ws2mschat: #消息发送topic
    addr: [ 127.0.0.1:9092 ] #kafka配置，默认即可
    topic: "ws2ms_chat" #用于mongo和mysql保存消息
  ms2pschat: # 消息推送的topic
    addr: [ 127.0.0.1:9092 ] #kafka配置，默认即可
    topic: "ms2ps_chat" #消息push
  consumergroupid: # 消费者组id
    msgToTransfer: mongo
    msgToMySql: mysql
    msgToPush: push

#---------------Internal service configuration---------------------#

# The service ip default is empty,
# automatically obtain the machine's valid network card ip as the service ip,
# otherwise the configuration ip is preferred
#如果是单机模式，用0.0.0.0或者不填，默认即可
serverip: 0.0.0.0

#作为rpc时，注册到etcd的地址，单机默认即可，如果是集群部署，需要修改（具体使用内网地址还是外网地址，要依情况而定，目的是api/gateway能访问到）
rpcRegisterIP:
#默认即可
listenIP: 0.0.0.0

api:
  openImApiPort: [ 10002 ] #api服务端口，默认即可，需要开放此端口或做nginx转发
  listenIP: 0.0.0.0
cmsapi:
  openImCmsApiPort: [ 10006 ] #管理后台api服务端口，默认即可，需要开放此端口或做nginx转发
  listenIP: 0.0.0.0

rpcport: #rpc服务端口 默认即可
  openImUserPort: [ 10110 ] # rpc 用户信息端口
  openImFriendPort: [ 10120 ] # rpc 好友信息端口
  openImMessagePort: [ 10130 ] # rpc im消息端口
  openImMessageGatewayPort: [ 10140 ] # rpc 消息网关端口
  openImPushPort: [ 10170 ] # rpc 推送端口
  openImAuthPort: [ 10160 ] # rpc 鉴权端口
rpcregistername: #rpc注册服务名，默认即可
  openImUserName: User
  openImMsgName: Msg
  openImPushName: Push
  openImRelayName: Relay
log:
  storageLocation: ../logs/  # 持久化地址
  rotationTime: 24 # 24小时
  remainRotationCount: 2 #日志数量
  #日志级别 6表示全都打印，测试阶段建议设置为6
  remainLogLevel: 6

modulename: #日志文件按模块命名，默认即可
  longConnSvrName: msg_gateway
  msgTransferName: msg_transfer
  pushName: push

longconnsvr:
  openImWsPort: [ 10001 ] # ws服务端口，默认即可，要开放此端口或做nginx转发
  websocketMaxConnNum: 10000 # 最大连接数
  websocketMaxMsgLen: 4096 # 最大读取消息
  websocketTimeOut: 10 # socket连接超时时间

manager:
  #app管理员userID和对应的secret  建议修改。 用于管理后台登录，也可以用户管理后台对应的api
  appManagerUid: [ "openIM123456","openIM654321", "openIM333", "openIMAdmin" ]
  secrets: [ "openIM1","openIM2", "openIM333", "openIMAdmin" ]
  appSysNotificationName: "系统通知"

# 注册，登录密钥配置
secret: 123456
# 多端互踢策略
# 1：多平台登录：Android、iOS、Windows、Mac 每种平台只能一个在线，web端可以多个同时在线
multiloginpolicy: 1

#msg log insert to db 持久化消息到mysql
chatpersistencemysql: true

#token config token相关配置
tokenpolicy:
  accessSecret:  #token生成相关，默认即可
  # Token effective time day as a unit
  accessExpire: 1 #token过期时间（天） 默认即可

# 回调配置
callback:
  # callback url 需要自行更换callback url
  callbackUrl: "http://127.0.0.1:8080/callback"
  # 开启关闭操作前后回调的配置
  callbackUserOnline: # 用户上线回调
    enable: false
    callbackTimeOut: 2
  callbackUserOffline: # 用户离线回调
    enable: false
    callbackTimeOut: 2
  callbackUserKickOff: # 用户被踢下线回调
    enable: false
    callbackTimeOut: 2
  callbackBeforeAddFriend: # 添加好友前回调
    enable: false
    callbackTimeOut: 2
    callbackFailedContinue: true

# prometheus每个服务监听的端口数量需要和rpc port保持一致
prometheus:
  messageGatewayPrometheusPort: [ 20140 ] ## 消息网关prometheus的端口

#---------------demo configuration---------------------#
#The following configuration items are applied to openIM Demo configuration
#是否启动demo，如果自身没有账号体系，设置为true
demo:
  #demo对外服务端口，默认即可，需要开放此端口或做nginx转发
  openImDemoPort: [ 10004 ]